//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Ratchet and Clank 3/Player/PlayerControlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControlls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControlls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControlls"",
    ""maps"": [
        {
            ""name"": ""Playstation Controlls"",
            ""id"": ""96eada3f-0ba2-4bd0-95ba-e2a71a4ed81b"",
            ""actions"": [
                {
                    ""name"": ""DoubleJump"",
                    ""type"": ""Button"",
                    ""id"": ""a3527a49-a197-4991-9593-362422965b14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ae80001e-6de4-4c9d-bd1c-2da8919adad9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""e15294ef-11ea-4077-b414-c2b7ce347e8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""f91531e7-3b15-465d-87fd-eee123c849a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": ""Invert"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wrench"",
                    ""type"": ""Button"",
                    ""id"": ""9894c724-8494-41c7-bb99-a41506f721c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSelect"",
                    ""type"": ""Button"",
                    ""id"": ""4fa405cf-c29e-4dfc-b676-abafd305c15f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""bf873c95-1d57-485f-b3f0-33c8261fdc27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Boots"",
                    ""type"": ""Button"",
                    ""id"": ""4b01ee8b-276c-4417-a30c-c61cdce857d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movment"",
                    ""type"": ""Value"",
                    ""id"": ""d643f043-9866-4dfd-883e-3f2545d81026"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f7b9c206-e4d0-4445-9def-413f3da7554a"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Playstation"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0a52a3f-77ef-42ad-998f-fc4222b54e1d"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Playstation"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6575d863-1a75-49aa-9006-ac048136c450"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": ""Invert"",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""138c500f-d1c6-46f6-9275-3d0aed274e37"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Playstation"",
                    ""action"": ""Wrench"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa2d972f-2bc6-413f-bb8b-a8610a8b2395"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Playstation"",
                    ""action"": ""QuickSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7e517d0-1b1c-4e6f-a8a0-153baa294569"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Playstation"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1241d45d-eccd-49ff-b91e-0be01b2ca8e1"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": ""Playstation"",
                    ""action"": ""Boots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7856bc4d-3c0c-4c56-80a7-d2b1bd2d8559"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": ""Playstation"",
                    ""action"": ""DoubleJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06071ce8-4db2-4e88-aed0-9f927bde3026"",
                    ""path"": ""<DualShockGamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": ""Playstation"",
                    ""action"": ""Movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94724106-5d37-48f4-89ae-b079b25de1d6"",
                    ""path"": ""<DualShockGamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Playstation"",
                    ""action"": ""Movment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Playstation"",
            ""bindingGroup"": ""Playstation"",
            ""devices"": []
        },
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": []
        }
    ]
}");
        // Playstation Controlls
        m_PlaystationControlls = asset.FindActionMap("Playstation Controlls", throwIfNotFound: true);
        m_PlaystationControlls_DoubleJump = m_PlaystationControlls.FindAction("DoubleJump", throwIfNotFound: true);
        m_PlaystationControlls_Jump = m_PlaystationControlls.FindAction("Jump", throwIfNotFound: true);
        m_PlaystationControlls_Crouch = m_PlaystationControlls.FindAction("Crouch", throwIfNotFound: true);
        m_PlaystationControlls_Shoot = m_PlaystationControlls.FindAction("Shoot", throwIfNotFound: true);
        m_PlaystationControlls_Wrench = m_PlaystationControlls.FindAction("Wrench", throwIfNotFound: true);
        m_PlaystationControlls_QuickSelect = m_PlaystationControlls.FindAction("QuickSelect", throwIfNotFound: true);
        m_PlaystationControlls_Menu = m_PlaystationControlls.FindAction("Menu", throwIfNotFound: true);
        m_PlaystationControlls_Boots = m_PlaystationControlls.FindAction("Boots", throwIfNotFound: true);
        m_PlaystationControlls_Movment = m_PlaystationControlls.FindAction("Movment", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Playstation Controlls
    private readonly InputActionMap m_PlaystationControlls;
    private IPlaystationControllsActions m_PlaystationControllsActionsCallbackInterface;
    private readonly InputAction m_PlaystationControlls_DoubleJump;
    private readonly InputAction m_PlaystationControlls_Jump;
    private readonly InputAction m_PlaystationControlls_Crouch;
    private readonly InputAction m_PlaystationControlls_Shoot;
    private readonly InputAction m_PlaystationControlls_Wrench;
    private readonly InputAction m_PlaystationControlls_QuickSelect;
    private readonly InputAction m_PlaystationControlls_Menu;
    private readonly InputAction m_PlaystationControlls_Boots;
    private readonly InputAction m_PlaystationControlls_Movment;
    public struct PlaystationControllsActions
    {
        private @PlayerControlls m_Wrapper;
        public PlaystationControllsActions(@PlayerControlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @DoubleJump => m_Wrapper.m_PlaystationControlls_DoubleJump;
        public InputAction @Jump => m_Wrapper.m_PlaystationControlls_Jump;
        public InputAction @Crouch => m_Wrapper.m_PlaystationControlls_Crouch;
        public InputAction @Shoot => m_Wrapper.m_PlaystationControlls_Shoot;
        public InputAction @Wrench => m_Wrapper.m_PlaystationControlls_Wrench;
        public InputAction @QuickSelect => m_Wrapper.m_PlaystationControlls_QuickSelect;
        public InputAction @Menu => m_Wrapper.m_PlaystationControlls_Menu;
        public InputAction @Boots => m_Wrapper.m_PlaystationControlls_Boots;
        public InputAction @Movment => m_Wrapper.m_PlaystationControlls_Movment;
        public InputActionMap Get() { return m_Wrapper.m_PlaystationControlls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlaystationControllsActions set) { return set.Get(); }
        public void SetCallbacks(IPlaystationControllsActions instance)
        {
            if (m_Wrapper.m_PlaystationControllsActionsCallbackInterface != null)
            {
                @DoubleJump.started -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnDoubleJump;
                @DoubleJump.performed -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnDoubleJump;
                @DoubleJump.canceled -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnDoubleJump;
                @Jump.started -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnJump;
                @Crouch.started -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnCrouch;
                @Shoot.started -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnShoot;
                @Wrench.started -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnWrench;
                @Wrench.performed -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnWrench;
                @Wrench.canceled -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnWrench;
                @QuickSelect.started -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnQuickSelect;
                @QuickSelect.performed -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnQuickSelect;
                @QuickSelect.canceled -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnQuickSelect;
                @Menu.started -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnMenu;
                @Boots.started -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnBoots;
                @Boots.performed -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnBoots;
                @Boots.canceled -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnBoots;
                @Movment.started -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnMovment;
                @Movment.performed -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnMovment;
                @Movment.canceled -= m_Wrapper.m_PlaystationControllsActionsCallbackInterface.OnMovment;
            }
            m_Wrapper.m_PlaystationControllsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @DoubleJump.started += instance.OnDoubleJump;
                @DoubleJump.performed += instance.OnDoubleJump;
                @DoubleJump.canceled += instance.OnDoubleJump;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Wrench.started += instance.OnWrench;
                @Wrench.performed += instance.OnWrench;
                @Wrench.canceled += instance.OnWrench;
                @QuickSelect.started += instance.OnQuickSelect;
                @QuickSelect.performed += instance.OnQuickSelect;
                @QuickSelect.canceled += instance.OnQuickSelect;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @Boots.started += instance.OnBoots;
                @Boots.performed += instance.OnBoots;
                @Boots.canceled += instance.OnBoots;
                @Movment.started += instance.OnMovment;
                @Movment.performed += instance.OnMovment;
                @Movment.canceled += instance.OnMovment;
            }
        }
    }
    public PlaystationControllsActions @PlaystationControlls => new PlaystationControllsActions(this);
    private int m_PlaystationSchemeIndex = -1;
    public InputControlScheme PlaystationScheme
    {
        get
        {
            if (m_PlaystationSchemeIndex == -1) m_PlaystationSchemeIndex = asset.FindControlSchemeIndex("Playstation");
            return asset.controlSchemes[m_PlaystationSchemeIndex];
        }
    }
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IPlaystationControllsActions
    {
        void OnDoubleJump(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnWrench(InputAction.CallbackContext context);
        void OnQuickSelect(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnBoots(InputAction.CallbackContext context);
        void OnMovment(InputAction.CallbackContext context);
    }
}
